{
 "title": "Performator Dashboard (Postgres)",
 "time": { "from": "2026-01-09T15:56:53.858Z", "to": "2026-01-09T16:00:53.840Z" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "grafana-postgresql-datasource" },
   {
    "name": "testid",
    "label": "Test",
    "query": "\t\tSELECT \n      id as \"__value\"\n    , concat(\n        to_char(\n            to_timestamp(time/1000)\n          , 'YYYY-MM-DD HH24:MI'\n        )\n        , to_char(\n            to_timestamp(endtime/1000)\n          , ' to HH24:MI'\n        )\n        , ' [', name, ']'\n      ) as \"__text\"\nFROM ${tableprefix}_tests\nORDER BY time desc"
   },
   { "name": "tableprefix", "query": "hsr" }
  ]
 },
 "panels": [
  {
   "title": "OK vs NOK",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, test\r\n\t\t\t, name\r\n\t\t\t, ok_count\r\n\t\t\t, nok_count\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = $testid \r\n\t\t  AND type != 'User'\r\n\t\t  AND type != 'System'\r\n\t\t  AND usecase != ''"
    }
   ]
  },
  {
   "title": "SLA OK vs NOK",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, test\r\n\t\t\t, name\r\n\t\t\t, ok_sla\r\n\t\t\t, nok_sla\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = $testid \r\n\t\t  AND type != 'User'\r\n\t\t  AND type != 'System'\r\n\t\t  AND usecase != ''\r\n\t\t  AND ok_sla >= 0"
    }
   ]
  },
  {
   "title": "Statuses",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, path\r\n\t\t\t, name\r\n\t\t\t, success\r\n\t\t\t, skipped\r\n\t\t\t, failed\r\n\t\t\t, aborted\r\n\t\t\t, none\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = $testid \r\n\t\t  AND type != 'User'\r\n\t\t  AND type != 'System'\r\n\t\t  AND usecase != ''\r\n\t\t  AND success >= 0\r\n\t\t  "
    }
   ]
  },
  {
   "title": "Messages",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t type\r\n\t\t\t, SUM(ok_count)\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = $testid \r\n\t\t  AND (\r\n\t\t  \t\ttype = 'MessageInfo'\r\n\t\t  \t OR type = 'MessageWarn'\r\n\t\t  \t OR type = 'MessageError'\r\n\t\t  )\r\nGROUP BY type\r\n\t\t"
    }
   ]
  },
  {
   "title": "CPU Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"percent\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'System'\r\n\t\t  AND name LIKE 'CPU Usage%'\r\n"
    }
   ]
  },
  {
   "title": "Host Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"percent\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'System'\r\n\t\t  AND name LIKE 'Host Memory%'\r\n"
    }
   ]
  },
  {
   "title": "Process Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"percent\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'System'\r\n\t\t  AND name = 'Process Memory Usage [%]'\r\n"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"MB\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'System'\r\n\t\t  AND name LIKE 'Process Memory%[MB]'\r\n"
    }
   ]
  },
  {
   "title": "Network I/O Received[MB/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"MB\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'System'\r\n\t\t  AND name LIKE 'Network I/O Recv%'\r\n"
    }
   ]
  },
  {
   "title": "Network I/O Sent[MB/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"MB\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'System'\r\n\t\t  AND name LIKE 'Network I/O Sent%'\r\n"
    }
   ]
  },
  {
   "title": "Disk I/O Read [MB/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"MB\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'System'\r\n\t\t  AND name LIKE 'Disk I/O Read%'\r\n"
    }
   ]
  },
  {
   "title": "Disk I/O Write [MB/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"MB\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'System'\r\n\t\t  AND name LIKE 'Disk I/O Write%'\r\n"
    }
   ]
  },
  {
   "title": "Users Total Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"users\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'User'\r\n\t\t  AND name = 'Active'\r\n\r\n\t\t  \r\n"
    }
   ]
  },
  {
   "title": "Users Total Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"users\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'User'\r\n\t\t  AND name = 'Started'\r\n\r\n\t\t  \r\n"
    }
   ]
  },
  {
   "title": "Users Total Stopped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"users\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'User'\r\n\t\t  AND name = 'Stopped'\r\n\r\n\t\t  \r\n"
    }
   ]
  },
  {
   "title": "Host Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, ok_count as \"percent\"\r\n\t\t\t, concat(path, ' ', name) as metric\r\n\t\t\t\r\n\t\tFROM ${tableprefix}_stats\r\n\t\tWHERE testid = ${testid}\r\n\t\t  AND type = 'System'\r\n\t\t  AND name LIKE 'Disk Usage%'\r\n"
    }
   ]
  },
  {
   "title": "Overall Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, min(ok_min) as \"min\"\r\n\t\t\t, avg(ok_avg) as \"avg\"\r\n\t\t\t, percentile_cont(0.90) within group (order by ok_p90 asc) as p90\r\n\t\t\t, max(ok_max) as \"max\"\r\nFROM ${tableprefix}_stats\r\nWHERE testid = ${testid}\r\n\t\tAND ok_count IS NOT NULL\r\n\t\tAND type != 'User'\r\n\t\tAND type != 'System'\r\n\t\tAND usecase != ''\r\nGROUP BY time \r\n"
    }
   ]
  },
  {
   "title": "Requests OK vs NOK",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t, sum(ok_count) as \"ok_count\"\r\n\t\t\t, sum(nok_count) as \"nok_count\"\r\nFROM ${tableprefix}_stats\r\nWHERE testid = $testid \r\n\t\tAND type != 'User'\r\n\t\tAND type != 'System'\r\n\t\tAND usecase != ''\r\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Requests By Status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t\t  time\r\n\t\t\t,\tcode\r\n\t\t\t, sum(ok_count + nok_count) as \"count\"\r\nFROM ${tableprefix}_stats\r\nWHERE testid = $testid \r\n\t\tAND type != 'User'\r\n\t\tAND type != 'System'\r\n\t\tAND usecase != ''\r\n\t\tAND code != ''\r\nGROUP BY time, code\r\n\r\n\t\t  "
    }
   ]
  },
  {
   "title": "Statistics by Metric",
   "type": "table",
   "gridPos": { "h": 18, "w": 23, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n\t\t  type\r\n\t\t, name\r\n\t\t, CASE\r\n\t          WHEN type IN ('Gauge', 'System', 'User') THEN AVG(ok_count)\r\n\t          ELSE SUM(ok_count)\r\n\t      END AS \"count(ok)\"\r\n\t\t, sum(nok_count) as \"count(nok)\"\r\n\t\t, min(ok_min) as \"min\"\r\n\t\t, round(avg(ok_avg), 1) as \"avg\"\r\n\t\t, max(ok_max) as \"max\"\r\n\t\t, round(avg(ok_stdev), 1) as \"stdev\"\r\n\t\t, percentile_disc(0.25) within group (order by ok_p25 asc) as p25\r\n\t\t, percentile_disc(0.50) within group (order by ok_p50 asc) as p50\r\n\t\t, percentile_disc(0.75) within group (order by ok_p75 asc) as p75\r\n\t\t, percentile_disc(0.90) within group (order by ok_p90 asc) as p90\r\n\t\t, percentile_disc(0.95) within group (order by ok_p95 asc) as p95\r\n\t\t, percentile_disc(0.99) within group (order by ok_p99 asc) as p99\r\nFROM ${tableprefix}_stats\r\nWHERE testid = $testid \r\n\t\tAND ok_count IS NOT NULL\r\n\t\t  AND type != 'User'\r\n\t\t  AND type != 'System'\r\n\t\t  AND usecase != ''  \r\nGROUP BY type, name\r\n\r\n\r\n\r\n\t"
    }
   ]
  }
 ]
}